"""Reproducible data-quality and leakage audit -> reports/data_audit.md

    python scripts/audit.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from kestrel_fraud.config import REPORT_DIR  # noqa: E402
from kestrel_fraud.data import (AUTO_APPROVAL_LIMIT_INR, AUTO_APPROVAL_START, TARGET, load_raw,  # noqa: E402
                                normalise_fault, serial_format)

LEAKAGE_TABLE = """
| Field | Known before payout? | Used? | Note |
|---|---|---|---|
| claim_id | yes | no | identifier only |
| submitted_at | yes | yes (as time context, partner windows, policy regime) | never as a raw trend feature |
| partner_id | yes | indirectly | via point-in-time partner history; the ID itself is not a feature |
| sku → family, list price, warranty months | yes | yes | reference data |
| product_serial | yes | format only | typed by the partner; raw value too noisy |
| days_since_purchase, claim_amount_inr, photo_attached, customer_prior_claims | yes | yes | |
| partner_inspected, inspector_note | yes (inspection precedes approval, policy §5) | yes (note as a fixed category) | after 1 May 2026 small claims have no inspection by design |
| claim_description | yes | fault category only | free text after the fault phrase is ignored (untrusted partner input) |
| source | yes | no | system of record; perfectly correlated with date (Zoho before Oct 2025), not with fraud |
| is_fraud | **no – outcome** | target only | blanks (undecided) excluded |
| partner fraud history | only outcomes closed before the claim | yes | 30-day closure lag + export cutoff; leakage test in tests/test_leakage.py |
| partners.onboarded_date / city / type | yes | tenure & type (city not used) | tenure computed at claim time |
"""


def md(df: pd.DataFrame) -> str:
    """Minimal markdown table (avoids an extra tabulate dependency)."""
    df = df.reset_index()
    head = "| " + " | ".join(map(str, df.columns)) + " |"
    sep = "|" + "---|" * len(df.columns)
    rows = ["| " + " | ".join(str(v) for v in r) + " |" for r in df.itertuples(index=False)]
    return "\n".join([head, sep, *rows])


def main():
    train, test, partners, products = load_raw()
    L = []
    w = L.append
    w("# Data audit (generated by scripts/audit.py)\n")
    for name, d in [("train.csv", train), ("test_unlabelled.csv", test), ("partners.csv", partners), ("products.csv", products)]:
        w(f"## {name}: {d.shape[0]} rows × {d.shape[1]} cols\n")
        info = pd.DataFrame({"dtype": d.dtypes.astype(str), "missing": d.isna().sum(), "unique": d.nunique()})
        w(md(info) + "\n")
    tr = train.assign(ts=pd.to_datetime(train.submitted_at, errors="coerce"))
    te = test.assign(ts=pd.to_datetime(test.submitted_at, errors="coerce"))
    w("## Checks\n")
    dup = tr[tr.claim_id.duplicated(keep=False)]
    gaps = dup.groupby("claim_id").ts.agg(lambda s: (s.max() - s.min()).days)
    other_cols = [c for c in train.columns if c not in ("submitted_at",)]
    identical = (dup.groupby("claim_id")[other_cols].nunique(dropna=False) <= 1).all(axis=1).mean()
    pa = partners.assign(onb=pd.to_datetime(partners.onboarded_date))
    trp = tr.merge(pa, on="partner_id", how="left")
    tep = te.merge(pa, on="partner_id", how="left")
    checks = {
        "unparseable submitted_at (train/test)": f"{tr.ts.isna().sum()} / {te.ts.isna().sum()}",
        "train date range": f"{tr.ts.min()} → {tr.ts.max()}",
        "test date range": f"{te.ts.min()} → {te.ts.max()}",
        "train rows with repeated claim_id (re-submissions)": f"{len(dup)} rows / {dup.claim_id.nunique()} claims; "
                                                              f"gap {gaps.min()}–{gaps.max()} days; identical apart from timestamp: {identical:.0%}",
        "fully duplicated rows": int(train.duplicated().sum()),
        "test duplicate claim_id": int(test.claim_id.duplicated().sum()),
        "claim_id overlap train/test": len(set(train.claim_id) & set(test.claim_id)),
        "orphan partner_id / sku (train+test)": f"{len((set(train.partner_id) | set(test.partner_id)) - set(partners.partner_id))} / "
                                                f"{len((set(train.sku) | set(test.sku)) - set(products.sku))}",
        "claims before partner onboarding": int(((trp.ts - trp.onb).dt.days < 0).sum() + ((tep.ts - tep.onb).dt.days < 0).sum()),
        "claim_amount > list price": int((tr.merge(products, on="sku").eval("claim_amount_inr > list_price_inr")).sum()),
        "claim_amount <= 0 / days_since_purchase < 0": f"{int((train.claim_amount_inr <= 0).sum())} / {int((train.days_since_purchase < 0).sum())}",
        "claims beyond warranty_months": int((tr.merge(products, on="sku").eval("days_since_purchase > warranty_months * 30.44")).sum()),
        "is_fraud values": str(train[TARGET].value_counts(dropna=False).to_dict()),
        "undecided (blank) by source": str(train[train[TARGET].isna()].source.value_counts().to_dict()),
        "legacy_zoho rows / blanks among them": f"{(train.source == 'legacy_zoho').sum()} / {train[train.source == 'legacy_zoho'][TARGET].isna().sum()} (Zoho stored blanks as 0)",
        "descriptions with text appended after the fault phrase": int((train.claim_description.str.len() > 40).sum() + (test.claim_description.str.len() > 40).sum()),
        "serial formats (train)": str(train.product_serial.map(serial_format).value_counts().to_dict()),
        "partners onboarded after train end (no history at all)": int((pa.onb > tr.ts.max()).sum()),
    }
    w(md(pd.Series(checks, name="result").to_frame()) + "\n")

    trd = tr.sort_values("ts").drop_duplicates("claim_id")
    trd = trd[trd[TARGET].notna()]
    trd["month"] = trd.ts.dt.to_period("M").astype(str)
    m = trd.groupby("month").agg(claims=(TARGET, "size"), fraud=(TARGET, "sum"),
                                 inspected=("partner_inspected", lambda s: (s == "Y").mean()),
                                 under_2000=("claim_amount_inr", lambda s: (s < AUTO_APPROVAL_LIMIT_INR).mean()))
    m["fraud_rate"] = m.fraud / m.claims
    w("## Monthly profile (decided, de-duplicated)\n")
    w(md(m.round(4)) + "\n")
    w(f"Overall prevalence {trd[TARGET].mean():.4f}; majority-class ('nothing is fraud') accuracy {1 - trd[TARGET].mean():.4f}.\n")
    post = trd[trd.ts >= AUTO_APPROVAL_START]
    w(f"Since 1 May 2026: prevalence {post[TARGET].mean():.4f}; majority-class accuracy {1 - post[TARGET].mean():.4f}.\n")
    w("## Leakage audit\n" + LEAKAGE_TABLE)
    (REPORT_DIR / "data_audit.md").write_text("\n".join(L))
    print("\n".join(L))


if __name__ == "__main__":
    main()
